### ISSUE TITLE
Wishlist - needs adding as a separate link

### ISSUE THREAD

**Issue by TeriForey** [RSE-leaders/SORSE20#36]
Currently if people wish to suggest topics/speakers they're invited to do so within the topic bazaar - but this isn't really the best place for it.

I suggest we create a gwdg pad where we can list suggested speakers and topics, people can then add whatever they like to it. As I'm on the bazaar team, and we said we're happy to look this over every now and then to make sure it's not been defaced/deleted. 

I've not created a gwdg pad before so not sure what the best way of doing this is, but I'm happy to do it, if we agree this is a good way forward.

**Comment by Chilipp** [comment]
@TeriForey what are the next steps here?

**Comment by TeriForey** [comment]
So we need to either embed it on a new page, or just have a little blurb and a link to the pad that Stephan created. Probably want to advertise it (or just show it in the nav) on the landing page. There's also a bit in the FAQ that talks about it and will need editing - currently has a missing link to the topic bazaar which is wrong. 

I was planning on doing this tomorrow but if you've got time feel free to make a start :)

**Comment by Chilipp** [comment]
I wonder if it makes sense to have something like @vsoch implemented on [rseng.github.io](https://rseng.github.io/needs-love/): [Needs love](https://rseng.github.io/2020/needs-love/). What do you think @TeriForey and @vsoch? This would not go via GWDG pad but instead use a [github issue](https://github.com/rseng/needs-love/issues/new/choose) that is then shown on our webpage.

**Comment by Chilipp** [comment]
To get the Github averse people on board, we could also write a little web app using Heroku that takes a simple form and puts that as an issue on Github. I did something like this [on one of my previous projects](https://empd2.github.io/?tab=report-issue) that had non-programmers as target audience. This might be a little overkill, however.

**Comment by TeriForey** [comment]
I think that's overkill - we really just need a place for people to write their suggestions and stick an emoji/plus next to others. It's not for starting a conversation and doesn't need any kind of tracking so I think a GWDG pad is the right tool for it

**Comment by Chilipp** [comment]
alright :) With the current implementation at GWDG, embedding pads in external webpages does not work. So we can only add a little blurb and a link to it, and add it to the navigation. If you can do this tomorrow, that would be great, than I can work on other stuff as there are still [a couple of open issues for the launch next week](https://github.com/RSE-leaders/SORSE20/milestone/1).

**Comment by Chilipp** [comment]
Hey @vsoch! Sure, the code is open-source under GPL-3.0 license at https://github.com/EMPD2/EMPD-admin/. When I started it, Github CI was not yet there where it is today which is why I use a Docker/Heroku combination to host a tornado webserver for free. The code is not yet fully documented and I will (hopefully) submit a software paper in the next couple of months, but the important entrypoints are the [ViewerIssuesHandler](https://github.com/EMPD2/EMPD-admin/blob/76c73aea3a0fcd293770a0ce96031a82685d4e41/empd_admin/webapp.py#L350) and [VerificationHandler](https://github.com/EMPD2/EMPD-admin/blob/76c73aea3a0fcd293770a0ce96031a82685d4e41/empd_admin/webapp.py#L402) class. I try to summarize this here: The HTML-site makes a POST request to the URL of the heroku app which validates it using Googles recaptcha. A random token is generated and a verification mail with a link and the token is sent to the submitter. When the link is clicked, I am using a Github personal access token and [pygithub](https://pygithub.readthedocs.io/en/latest/) to open an issue on behalf of the submitter.

I never worked with dispatched workflows so far, but I think you can also use this instead of heroku.

> I still don't know what a pad is, must not be a thing in the US, or maybe it's just me!

Yep, this was also new to me until I started to work with de-RSE :wink: It's using CodiMD that is basically GoogleDocs but based on Markdown. Just click on the link from @sdruskat above (https://pad.gwdg.de/RsfrADceRp2dc_myoTy9hw#) and type something in the text field, and you'll immediately understand.

**Comment by vsoch** [comment]
Thank you! Yes and I see the GitHub token [here](https://github.com/EMPD2/EMPD-admin/blob/master/empd_admin/webapp.py#L151). I haven't used heroku for a few years, but I definitely think I might give it another go! I also like your trick for sending the verification email, that's a good idea.
